=== Nikhilpatel03/xml-and-js-course/quiz/quiz.dtd
<!ELEMENT products (product+)>
<!ELEMENT product (productName,availableSizes,prices)+>
<!ATTLIST product id ID #REQUIRED>
<!ELEMENT productName (#PCDATA)>
<!ELEMENT availableSizes (size+)>
<!ELEMENT size (#PCDATA)>
<!ATTLIST size description CDATA #REQUIRED>
<!ELEMENT prices (price+)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price currency CDATA #REQUIRED>

=== Nikhilpatel03/xml-and-js-course/quiz/quiz.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="quiz.xsl" type="text/xsl"?>
<!DOCTYPE products SYSTEM "quiz.dtd">
<products>
    <product id="a332d8d2-86d7-11ec-a8a3-0242ac120002">
        <productName>Microfleece hoodie</productName>
        <availableSizes>
            <size description="xs">0 items</size>
            <size description="s">3 items</size>
            <size description="m">13 items</size>
            <size description="l">5 items</size>
            <size description="xl">2 items</size>
        </availableSizes>
        <prices>
            <price currency="USD">USD&#36;49.99</price>
            <price currency="CAD">CAD&#36;59.99</price>
        </prices>
    </product>
    <product id="a332dac6-86d7-11ec-a8a3-0242ac120002">
        <productName>Vintage Soft Hoodie</productName>
        <availableSizes>
            <size description="xs">3 items</size>
            <size description="s">8 items</size>
            <size description="m">25 items</size>
            <size description="l">12 items</size>
            <size description="xl">4 items</size>
        </availableSizes>
        <prices>
            <price currency="USD">USD&#36;39.99</price>
            <price currency="CAD">CAD&#36;49.99</price>
        </prices>
    </product>
    <product id="a332dbf2-86d7-11ec-a8a3-0242ac120002">
        <productName>Crewneck Sweatshirt</productName>
        <availableSizes>
            <size description="xs">0 items</size>
            <size description="s">0 items</size>
            <size description="m">15 items</size>
            <size description="l">13 items</size>
            <size description="xl">0 items</size>
        </availableSizes>
        <prices>
            <price currency="CAD">CAD&#36;47.97</price>
        </prices>
    </product>
    <product id="a332dd0a-86d7-11ec-a8a3-0242ac120002">
        <productName>French Terry Raglan Crewneck Sweatshirt</productName>
        <availableSizes>
            <size description="xs">0 items</size>
            <size description="s">0 items</size>
            <size description="m">0 items</size>
            <size description="l">1 items</size>
            <size description="xl">0 items</size>
        </availableSizes>
        <prices>
            <price currency="USD">USD&#36;37.97</price>
        </prices>
    </product>
</products>
